### ISSUE TITLE
form-select

### ISSUE THREAD

**Issue by Grzegozr** [michalkortas/laravelforms#6]
![image](https://user-images.githubusercontent.com/40267810/91076907-7bf26500-e640-11ea-9963-e20478571f82.png)
![image](https://user-images.githubusercontent.com/40267810/91076952-8c0a4480-e640-11ea-9634-e20b8182db14.png)
![image](https://user-images.githubusercontent.com/40267810/91076975-9a586080-e640-11ea-8a17-8ad139919fe4.png)

**Comment by michalkortas** [comment]
Your collection need to be object-collection instead array-collection.

`
$collect = collect([
     (object)['type'=>'days', 'name'=>'dni'],
     (object)['type'=>'months', 'name'=>'miesiące']
]);
`

Then this code works.

`
<x-form-select option-value-key="type" option-text-key="name" :options="$collect"  />
`
